version: 2

jobs:
    build:
        working_directory: ~/redux-store-element
        docker:
            - image: circleci/node:8.1.2
        steps:
            - checkout
            - run:
                name: Install Bower dependencies
                command: sudo npm install -g bower && bower install
            - run: npm test
