version: 2

jobs:
    build:
        working_directory: ~/redux-store-element
        docker:
            - image: circleci/node:8.1.4
        steps:
            - checkout
            - run:
                name: Install Bower dependencies
                command: npm install bower && node_modules/.bin/bower install
